# Generated by Django 5.2.5 on 2025-09-23 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва кафедри')),
                ('head', models.CharField(max_length=200, verbose_name='Завідувач кафедри')),
            ],
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='content',
            field=models.TextField(verbose_name='Текст головної сторінки'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва спеціальності')),
                ('code', models.CharField(max_length=20, verbose_name='Код спеціальності')),
                ('description', models.TextField(verbose_name='Опис спеціальності')),
                ('coordinator_name', models.CharField(max_length=200, verbose_name="Ім'я координатора набору")),
                ('coordinator_contact', models.CharField(max_length=200, verbose_name='Контакт координатора набору')),
                ('disciplines', models.TextField(verbose_name='Список дисциплін')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='faculty.department', verbose_name='Випускова кафедра')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Ім'я викладача")),
                ('position', models.CharField(max_length=200, verbose_name='Посада')),
                ('degree', models.CharField(max_length=200, verbose_name='Науковий ступінь')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='faculty.department', verbose_name='Кафедра')),
            ],
        ),
    ]
